---
- name: Create the brandon user
  become: yes
  ansible.builtin.user:
    name: brandon
    create_home: yes
    group: wheel

- name: Allow brandon to run pacman without password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-brandon
    line: 'brandon ALL=(ALL) NOPASSWD: /usr/bin/dmesg, /usr/bin/mount, /usr/bin/pacman, /usr/bin/umount'
    create: yes
    validate: 'visudo -cf %s'
