---
- name: Install packages for brandon
  include_tasks: packages.yml
  tags:
    - audio
    - aur
    - packages

- name: Install Uxn & ROMs
  include_tasks: uxn.yml
  tags: uxn

- name: Install packages for vst development
  include_tasks: vst.yml
  tags:
   - audio
   - vst

- name: Enable & start bluetooth daemon
  include_tasks: bluetooth.yml
  tags:
    - audio
    - bluetooth
