- name: Install audio packages
  pacman:
    name:
      - ardour
      - bluez
      - bluez-utils
      - calf
      - dragonfly-reverb
      - pipewire
      - pipewire-alsa
      - pipewire-audio
      - pipewire-jack
      - pipewire-pulse
      - qpwgraph
      - vlc
      - wireplumber
    state: present

- name: Install bitwig-studio
  kewlfft.aur.aur:
    name: bitwig-studio
    use: makepkg
    state: present
  become: yes
  become_user: brandon
