- name: Install audio packages
  pacman:
    name:
      - ardour
      - bluez
      - bluez-utils
      - calf
      - dragonfly-reverb
      - ecasound
      - pd
      - pipewire
      - pipewire-alsa
      - pipewire-audio
      - pipewire-jack
      - pipewire-pulse
      - qpwgraph
      - reaper
      - sox
      - supercollider
      - vlc
      - wireplumber
      - yabridge
      - yabridgectl
    state: present
  tags: packages

- name: Install audio AUR packages
  kewlfft.aur.aur:
    name:
      - bitwig-studio
    use: makepkg
    state: present
  become: yes
  become_user: brandon
  tags: aur
