---
- name: Install uxn dependencies
  pacman:
    name:
      - sdl2
    state: present
  tags: uxn

- name: Clone uxn
  ansible.builtin.git:
    repo: https://git.sr.ht/~rabbits/uxn
    dest: /home/brandon/www/uxn
  become: yes
  become_user: brandon
  tags: uxn

- name: Install uxn
  ansible.builtin.shell: |
    cd /home/brandon/www/uxn
    ./build.sh --no-run
    cp ./bin/uxn* /home/brandon/.local/bin/
  ignore_errors: true
  tags: uxn

- name: Clone orca
  ansible.builtin.git:
    repo: https://git.sr.ht/~rabbits/orca-toy
    dest: /home/brandon/www/orca-toy
  become: yes
  become_user: brandon
  tags: uxn

- name: Install orca
  ansible.builtin.shell: |
    cd /home/brandon/builds/orca-toy
    mkdir -p /home/brandon/www/orca-toy/bin
    uxnasm src/orca.tal /home/brandon/www/orca-toy/bin/orca.rom
  become: yes
  become_user: brandon
  ignore_errors: true
  tags: uxn
