---
- name: Install nvm
  kewlfft.aur.aur:
    name: nvm
    use: makepkg
    state: present
  become: yes
  become_user: brandon

- name: Install qFlipper
  kewlfft.aur.aur:
    name: qflipper-git
    use: makepkg
    state: present
  become: yes
  become_user: brandon

- name: Install viber
  kewlfft.aur.aur:
    name: viber
    use: makepkg
    state: present
  become: yes
  become_user: brandon

- name: Install vscode
  kewlfft.aur.aur:
    name: visual-studio-code-bin
    use: makepkg
    state: present
  become: yes
  become_user: brandon
