---
- name: Copy .xinitrc
  ansible.builtin.copy:
    src: ../files/config/.xinitrc
    dest: /home/brandon/.xinitrc
    owner: brandon
    group: wheel
    mode: u=rw,g=r,o=r
    backup: yes
  tags: config

- name: Copy .xprofile
  ansible.builtin.copy:
    src: ../files/config/.xprofile
    dest: /home/brandon/.xprofile
    owner: brandon
    group: wheel
    mode: u=rwx,g=r,o=r
    backup: yes
  tags: config

- name: Copy .vimrc
  ansible.builtin.copy:
    src: ../files/config/.vimrc
    dest: /home/brandon/.vimrc
    owner: brandon
    group: wheel
    mode: u=rwx,g=r,o=r
  tags: config

- name: Copy .zprofile
  ansible.builtin.copy:
    src: ../files/config/.zprofile
    dest: /home/brandon/.zprofile
    owner: brandon
    group: wheel
    mode: u=rw,g=r,o=r
  tags: config

- name: Copy .zshrc
  ansible.builtin.copy:
    src: ../files/config/.zshrc
    dest: /home/brandon/.zshrc
    owner: brandon
    group: wheel
    mode: u=rw,g=r,o=r
  tags: config

- name: Set zsh as shell of choice
  user:
    name: brandon
    shell: /usr/bin/zsh
  tags: config

#- name: Copy newsboat urls
#  ansible.builtin.copy:
#    src: ../files/config/.newsboat/urls
#    dest: /home/brandon/.newsboat/urls
#    owner: brandon
#    group: wheel
#    mode: u=rw,g=r,o=r
#  tags: config
