---
- name: Copy libinput for X
  ansible.builtin.copy:
    src: ../files/config/libinput
    dest: /etc/X11/xorg.conf.d/99-brandon.conf
    owner: brandon
    group: wheel
    mode: u=rw,g=r,o=r
  tags: config

- name: Copy .xinitrc
  ansible.builtin.copy:
    src: ../files/config/.xinitrc
    dest: /home/brandon/.xinitrc
    owner: brandon
    group: wheel
    mode: u=rw,g=r,o=r
    backup: yes
  tags: config

- name: Copy .xprofile
  ansible.builtin.copy:
    src: ../files/config/.xprofile
    dest: /home/brandon/.xprofile
    owner: brandon
    group: wheel
    mode: u=rwx,g=r,o=r
    backup: yes
  tags: config

- name: Copy .vimrc
  ansible.builtin.copy:
    src: ../files/config/.vimrc
    dest: /home/brandon/.vimrc
    owner: brandon
    group: wheel
    mode: u=rwx,g=r,o=r
  tags: config

- name: Copy .zprofile
  ansible.builtin.copy:
    src: ../files/config/.zprofile
    dest: /home/brandon/.zprofile
    owner: brandon
    group: wheel
    mode: u=rw,g=r,o=r
  tags: config

- name: Copy .zshrc
  ansible.builtin.copy:
    src: ../files/config/.zshrc
    dest: /home/brandon/.zshrc
    owner: brandon
    group: wheel
    mode: u=rw,g=r,o=r
  tags: config

- name: Set zsh as shell of choice
  user:
    name: brandon
    shell: /usr/bin/zsh
  tags: config
