---
- name: Create ~/www
  ansible.builtin.file:
    path: /home/brandon/www
    state: directory
    owner: brandon
    group: wheel

- name: Create ~/.local/bin
  ansible.builtin.file:
    path: /home/brandon/.local/bin
    state: directory
    owner: brandon
    group: wheel

- name: Copy scripts into ~/.local/bin
  ansible.builtin.copy:
    src: ../files/scripts/
    dest: /home/brandon/.local/bin
    owner: brandon
    group: wheel
    mode: u=rwx,g=r,o=r
