- name: Install docker
  pacman:
    name:
      - docker
      - docker-compose
  tags: docker

- name: Enable docker.service (daemon)
  ansible.builtin.systemd:
    name: docker.service
    enabled: yes
    state: started
  tags: docker

- name: Add brandon to the docker group
  ansible.builtin.user:
    name: brandon
    append: true
    groups: docker
  tags: docker
