---
- name: Install packages
  pacman:
    name:
      - arduino
      - aws-cli-v2
      - bitwarden
      - bitwarden-cli
      - blender
      - code
      - cups
      - gimp
      - go
      - jq
      - libreoffice-still
      - lynx
      - octave
      - pcmanfm
      - python
      - rustup
      - sxiv
      - terraform
      - thunderbird
      - ttf-hack
      - whois
      - wireshark-cli
      - wireshark-qt
      - xcompmgr
      - xorg-xwd
      - xwallpaper
    state: present
  tags: packages

- name: Install AUR packages
  kewlfft.aur.aur:
    name:
      - authy
      - httptoolkit-bin
      - nvm
      - opensnitch
      - qFlipper
      - timeshift
      - viber
    use: makepkg
    state: present
  become: yes
  become_user: brandon
  tags:
    - packages
    - aur
