---
- name: Install packages
  pacman:
    name:
      - bitwarden
      - bitwarden-cli
      - docker
      - docker-compose
      - go
      - ttf-hack
      - wine
      - winetricks
    state: present
