---
- name: Copy scripts/aliases
  ansible.builtin.copy:
    src: ../files/scripts/AxeFxIII
    dest: /home/brandon/.local/bin/AxeFxIII
    owner: brandon
    group: wheel
    mode: u=rwx,g=rx,o=rx
  tags: wine
	
