---
- name: Enable thinkpad_acpi.fan_control in GRUB
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet"'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet thinkpad_acpi.fan_control=1"'
  become: yes

- name: Regenerate bootloader GRUB config
  shell: grub-mkconfig -o /boot/grub/grub.cfg
