---
- name: Install Thinkpad-related packages
  include_tasks: packages.yml
  tags:
    - packages

- name: Add udev rule to allow use of xbacklight without sudo
  include_tasks: udev.yml
  tags:
   - thinkpad

- name: Copy libinput config
  include_tasks: config.yml
  tags:
    - thinkpad
