---
- name: Set hostname
  include_tasks: hostname.yml

- name: Enable additional repositories
  include_tasks: repo.yml

- name: Install base packages
  include_tasks: packages.yml
  tags: packages

  #- name: Configure GRUB
  # include_tasks: grub.yml

- name: Configure networking
  include_tasks: networking.yml

- name: Setup samba credentials
  include_tasks: samba.yml
  tags: samba
