- name: Install base dependencies
  pacman:
    name:
      - acpi
      - base
      - base-devel
      - dhcpcd
      - dosfstools
      - efibootmgr
      - firefox
      - firefox-ublock-origin
      - git
      - gparted
      - grub
      - iwd
      - ldns
      - linux
      - linux-firmware
      - linux-rt
      - lsof
      - man-db
      - mtools
      - pacman-contrib
      - reflector
      - smbclient
      - tcpdump
      - tmux
      - traceroute
      - unarchiver
      - usbutils
      - vim
      - xclip
      - xorg-xinit
      - xorg-server
      - xterm
      - zsh
    state: present
  tags: packages
